### ISSUE TITLE
Large git repo = unnacceptable performance

### ISSUE THREAD

**Issue by hildjj** [fishpkg/fish-git-util#6]
The metro theme uses git_util pretty heavily in it's [prompt](https://github.com/fisherman/metro/blob/master/fish_prompt.fish).  For large repos, such as [Firefox](https://github.com/mozilla/gecko-dev), rendering the prompt takes 5+ *seconds*, after each command.  The approaches I've come up with so far:

1.  Turn off git-flavored prompts in this directory, based on the presence of a dot file I can put in `~/.gitignore_global`
1.  Figure out faster ways of getting the current state out of git, including sending some sort of porcelain patch to git
1.  Switch to bash in this directory manually

Any other ideas?

**Comment by stefanmaric** [comment]
These are the `git_util`'s functions I see are being called in [that prompt](https://github.com/fisherman/metro/blob/master/fish_prompt.fish):

```
git_ahead
git_branch_name
git_is_detached_head
git_is_dirty
git_is_staged
git_is_stashed
git_is_touched
```

You might run the following inside that repo to know what functions are slowing down the prompt:

```shell
set -l git_command_list git_ahead git_branch_name git_is_detached_head git_is_dirty git_is_staged git_is_stashed git_is_touched
for c in $git_command_list
    echo
    echo "$c:"
    time -p fish -c "$c"
end
```

But I guess there's a cost of traveling a big working directory tree and there's little to do to improve these functions' performance since they pretty much rely on git's performance (which is arguably pretty good) so one could simply find git commands that perform better than others for the same purpose.

**Comment by hildjj** [comment]
It looks like `git_is_touched` and `git_is_dirty` are the worst offenders on my setup today.

```
git_ahead:

real         0.02
user         0.01
sys          0.00

git_branch_name:
master
real         0.02
user         0.01
sys          0.00

git_is_detached_head:
real         0.02
user         0.01
sys          0.00

git_is_dirty:
real         0.25
user         0.13
sys          0.41

git_is_staged:
real         0.11
user         0.08
sys          0.02

git_is_stashed:
real         0.02
user         0.01
sys          0.00

git_is_touched:
real         0.71
user         0.34
sys          0.63
```

**Comment by jbucaran** [comment]
This always comes to mind https://github.com/sindresorhus/pure/issues/115

**Comment by fishpkg** [comment]
Pull requests are appreciated (PR-based issue discussions work too!)! 👋
